// Столбцы таблицы для добавления в базу рассчитанных животных
const columnsInCalculatedBullTable = [
    'id',
    'naab_code',
    'inter_reg_number',
    'inventory_number',
    'name',
    'full_name',
    'breed',
    'tpi',
    'nm_dollar',
    'cm_dollar',
    'fm_dollar',
    'gm_dollar',
    'milk',
    'protein',
    'prot_percent',
    'fat',
    'fat_percent',
    'cfp',
    'fe',
    'feed_saved',
    'prel',
    'd_h',
    'pl',
    'c_liv',
    'h_liv',
    'fi',
    'dpr',
    'scs',
    'sce',
    'sce_rel',
    'sce_obs',
    'dce',
    'ssb',
    'dsb',
    'ccr',
    'hcr',
    'efc',
    'gl',
    'mast',
    'ket',
    'rp',
    'met',
    'da',
    'mf',
    'ms',
    'dwp_dollar',
    'wt_dollar',
    'cw_dollar',
    'ptat',
    'udc',
    'flc',
    'bwc',
    'dc',
    't_rel',
    'd_h2',
    'stature',
    'strength',
    'body_depth',
    'dairy_form',
    'rump_angle',
    'thurl_width',
    'rlsv',
    'rlrv',
    'foot_angle',
    'fls',
    'f_udder_att',
    'r_udder_height',
    'rear_udder_width',
    'udder_cleft',
    'udder_depth',
    'ftp',
    'rtp',
    'rtp_sv',
    'teat_length',
    'pedigree',
    'aaa',
    'dms',
    'kappa_casein',
    'beta_casein',
    'bbr',
    'b_lact',
    'genetic_codes',
    'haplotypes',
    'rha',
    'efi',
    'birth_date',
    'proof',
    'adv',
    'gs',
    'fs',
    'num_511',
    'edge',
    'cp',
    'cp511',
];

export const columns = [
    {
        name: 'id',
        type: 'INT AUTO_INCREMENT PRIMARY KEY',
        columnNameInTable: 'id',
        ruColumnNameInTable: 'id',
        isDigit: true,
    },
    {
        name: 'naab_code',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'NAAB Code',
        ruColumnNameInTable: 'NAAB Код',
        isDigit: false,
    },
    {
        name: 'inter_reg_number',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'InterRegNumber',
        ruColumnNameInTable: 'InterRegNumber',
        isDigit: false,
    },
    {
        name: 'naab_code_trimmed',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'naab_code_trimmed',
        ruColumnNameInTable: 'naab_code_trimmed',
        isDigit: false,
    },
    {
        name: 'inter_reg_number_trimmed',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'inter_reg_number_trimmed',
        ruColumnNameInTable: 'inter_reg_number_trimmed',
        isDigit: false,
    },
    {
        name: 'inventory_number',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'InventoryNumber',
        ruColumnNameInTable: 'InventoryNumber',
        isDigit: false,
    },
    {
        name: 'name',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'Name',
        ruColumnNameInTable: 'Имя',
        isDigit: false,
    },
    {
        name: 'full_name',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'Full Name',
        ruColumnNameInTable: 'Full Name',
        isDigit: false,
    },
    {
        name: 'breed',
        type: "VARCHAR(16) DEFAULT ''",
        columnNameInTable: 'Breed',
        ruColumnNameInTable: 'Порода',
        isDigit: false,
    },
    {
        name: 'tpi',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'TPI',
        ruColumnNameInTable: 'TPI',
        isDigit: true,
    },
    {
        name: 'nm_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'NM$',
        ruColumnNameInTable: 'NM$',
        isDigit: true,
    },
    {
        name: 'cm_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'CM$',
        ruColumnNameInTable: 'CM$',
        isDigit: true,
    },
    {
        name: 'fm_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'FM$',
        ruColumnNameInTable: 'FM$',
        isDigit: true,
    },
    {
        name: 'gm_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'GM$',
        ruColumnNameInTable: 'GM$',
        isDigit: true,
    },
    {
        name: 'milk',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Milk',
        ruColumnNameInTable: 'Молоко',
        isDigit: true,
    },
    {
        name: 'protein',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Protein',
        ruColumnNameInTable: 'Белок',
        isDigit: true,
    },
    {
        name: 'prot_percent',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Prot%',
        ruColumnNameInTable: 'Prot%',
        isDigit: true,
    },
    {
        name: 'fat',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Fat',
        ruColumnNameInTable: 'Жир',
        isDigit: true,
    },
    {
        name: 'fat_percent',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Fat %',
        ruColumnNameInTable: 'Жир в %',
        isDigit: true,
    },
    {
        name: 'cfp',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'CFP',
        ruColumnNameInTable: 'CFP',
        isDigit: true,
    },
    {
        name: 'fe',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'FE',
        ruColumnNameInTable: 'FE',
        isDigit: true,
    },
    {
        name: 'feed_saved',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Feed Saved',
        ruColumnNameInTable: 'Feed Saved',
        isDigit: true,
    },
    {
        name: 'prel',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Prel',
        ruColumnNameInTable: 'Prel',
        isDigit: true,
    },
    {
        name: 'd_h',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'D / H',
        ruColumnNameInTable: 'D / H',
        isDigit: false,
    },
    {
        name: 'pl',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'PL',
        ruColumnNameInTable: 'PL',
        isDigit: true,
    },
    {
        name: 'c_liv',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'C-LIV',
        ruColumnNameInTable: 'C-LIV',
        isDigit: true,
    },
    {
        name: 'h_liv',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'H-LIV',
        ruColumnNameInTable: 'H-LIV',
        isDigit: true,
    },
    {
        name: 'fi',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'FI',
        ruColumnNameInTable: 'FI',
        isDigit: true,
    },
    {
        name: 'dpr',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'DPR',
        ruColumnNameInTable: 'DPR',
        isDigit: true,
    },
    {
        name: 'scs',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'SCS',
        ruColumnNameInTable: 'SCS',
        isDigit: true,
    },
    {
        name: 'mspd',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'MSPD',
        ruColumnNameInTable: 'MSPD',
        isDigit: true,
    },
    {
        name: 'mspd_rel',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'MSPD Rel',
        ruColumnNameInTable: 'MSPD Rel',
        isDigit: true,
    },
    {
        name: 'sce',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'SCE',
        ruColumnNameInTable: 'SCE',
        isDigit: true,
    },
    {
        name: 'sce_rel',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'SCE Rel',
        ruColumnNameInTable: 'SCE Rel',
        isDigit: true,
    },
    {
        name: 'sce_obs',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'SCE Obs',
        ruColumnNameInTable: 'SCE Obs',
        isDigit: true,
    },
    {
        name: 'dce',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'DCE',
        ruColumnNameInTable: 'DCE',
        isDigit: true,
    },
    {
        name: 'ssd',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'SSD',
        ruColumnNameInTable: 'SSD',
        isDigit: true,
    },
    {
        name: 'dsb',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'DSB',
        ruColumnNameInTable: 'DSB',
        isDigit: true,
    },
    {
        name: 'ccr',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'CCR',
        ruColumnNameInTable: 'CCR',
        isDigit: true,
    },
    {
        name: 'hcr',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'HCR',
        ruColumnNameInTable: 'HCR',
        isDigit: true,
    },
    {
        name: 'efc',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'EFC',
        ruColumnNameInTable: 'EFC',
        isDigit: true,
    },
    {
        name: 'gl',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'GL',
        ruColumnNameInTable: 'GL',
        isDigit: true,
    },
    {
        name: 'mast',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'MAST',
        ruColumnNameInTable: 'MAST',
        isDigit: true,
    },
    {
        name: 'ket',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'KET',
        ruColumnNameInTable: 'KET',
        isDigit: true,
    },
    {
        name: 'rp',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'RP',
        ruColumnNameInTable: 'RP',
        isDigit: true,
    },
    {
        name: 'met',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'MET',
        ruColumnNameInTable: 'MET',
        isDigit: true,
    },
    {
        name: 'da',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'DA',
        ruColumnNameInTable: 'DA',
        isDigit: true,
    },
    {
        name: 'mf',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'MF',
        ruColumnNameInTable: 'MF',
        isDigit: true,
    },
    {
        name: 'ms',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'MS',
        ruColumnNameInTable: 'MS',
        isDigit: true,
    },
    {
        name: 'dwp_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'DWP$',
        ruColumnNameInTable: 'DWP$',
        isDigit: true,
    },
    {
        name: 'wt_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'WT$',
        ruColumnNameInTable: 'WT$',
        isDigit: true,
    },
    {
        name: 'cw_dollar',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'CW$',
        ruColumnNameInTable: 'CW$',
        isDigit: true,
    },
    {
        name: 'ptat',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'PTAT',
        ruColumnNameInTable: 'PTAT',
        isDigit: true,
    },
    {
        name: 'udc',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'UDC',
        ruColumnNameInTable: 'UDC',
        isDigit: true,
    },
    {
        name: 'flc',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'FLC',
        ruColumnNameInTable: 'FLC',
        isDigit: true,
    },
    {
        name: 'bwc',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'BWC',
        ruColumnNameInTable: 'BWC',
        isDigit: true,
    },
    {
        name: 'dc',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'DC',
        ruColumnNameInTable: 'DC',
        isDigit: true,
    },
    {
        name: 't_rel',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'TRel',
        ruColumnNameInTable: 'TRel',
        isDigit: true,
    },
    {
        name: 'd_h2',
        type: "VARCHAR(32) DEFAULT ''",
        columnNameInTable: 'D / H',
        ruColumnNameInTable: 'D / H',
        isDigit: false,
    },
    {
        name: 'stature',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Stature',
        ruColumnNameInTable: 'Телосл-е',
        isDigit: true,
    },
    {
        name: 'strength',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Strength',
        ruColumnNameInTable: 'Сила',
        isDigit: true,
    },
    {
        name: 'body_depth',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Body Depth',
        ruColumnNameInTable: 'Глуб. тела',
        isDigit: true,
    },
    {
        name: 'dairy_form',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Dairy form',
        ruColumnNameInTable: 'Мол. форма',
        isDigit: true,
    },
    {
        name: 'rump_angle',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Rump Angle',
        ruColumnNameInTable: 'Угол крестца',
        isDigit: true,
    },
    {
        name: 'thurl_width',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Thurl Width',
        ruColumnNameInTable: 'Шир. таз-х с.',
        isDigit: true,
    },
    {
        name: 'rlsv',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'RLSV',
        ruColumnNameInTable: 'RLSV',
        isDigit: true,
    },
    {
        name: 'rlrv',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'RLRV',
        ruColumnNameInTable: 'RLRV',
        isDigit: true,
    },
    {
        name: 'foot_angle',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Foot Angle',
        ruColumnNameInTable: 'Угол копыта',
        isDigit: true,
    },
    {
        name: 'fls',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'FLS',
        ruColumnNameInTable: 'FLS',
        isDigit: true,
    },
    {
        name: 'f_udder_att',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'F. Udder Att.',
        ruColumnNameInTable: 'Пер. прик. вым.',
        isDigit: true,
    },
    {
        name: 'r_udder_height',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'R Udder Height',
        ruColumnNameInTable: 'R Udder Height',
        isDigit: true,
    },
    {
        name: 'rear_udder_width',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Rear Udder Width',
        ruColumnNameInTable: 'Шир. зад. части вым.',
        isDigit: true,
    },
    {
        name: 'udder_cleft',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Udder Cleft',
        ruColumnNameInTable: 'Расщ-е вым.',
        isDigit: true,
    },
    {
        name: 'udder_depth',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Udder Depth',
        ruColumnNameInTable: 'Глуб. вымени',
        isDigit: true,
    },
    {
        name: 'ftp',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'FTP',
        ruColumnNameInTable: 'FTP',
        isDigit: true,
    },
    {
        name: 'rtp',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'RTP',
        ruColumnNameInTable: 'RTP',
        isDigit: true,
    },
    {
        name: 'rtp_sv',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'RTP SV',
        ruColumnNameInTable: 'RTP SV',
        isDigit: true,
    },
    {
        name: 'teat_length',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'Teat Length',
        ruColumnNameInTable: 'Длина сосков',
        isDigit: true,
    },
    {
        name: 'pedigree',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'Pedigree',
        ruColumnNameInTable: 'Родосл.',
        isDigit: false,
    },
    {
        name: 'aaa',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'aAa',
        ruColumnNameInTable: 'aAa',
        isDigit: false,
    },
    {
        name: 'dms',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'DMS',
        ruColumnNameInTable: 'DMS',
        isDigit: false,
    },
    {
        name: 'kappa_casein',
        type: "VARCHAR(8) DEFAULT ''",
        columnNameInTable: 'Kappa-Casein',
        ruColumnNameInTable: 'Каппа казеин',
        isDigit: false,
    },
    {
        name: 'beta_casein',
        type: "VARCHAR(8) DEFAULT ''",
        columnNameInTable: 'Beta-Casein',
        ruColumnNameInTable: 'Бета казеин',
        isDigit: false,
    },
    {
        name: 'bbr',
        type: "VARCHAR(8) DEFAULT ''",
        columnNameInTable: 'BBR',
        ruColumnNameInTable: 'BBR',
        isDigit: false,
    },
    {
        name: 'b_lact',
        type: "VARCHAR(8) DEFAULT ''",
        columnNameInTable: 'B-LACT',
        ruColumnNameInTable: 'B-LACT',
        isDigit: false,
    },
    {
        name: 'genetic_codes',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'Genetic Codes',
        ruColumnNameInTable: 'Genetic Codes',
        isDigit: false,
    },
    {
        name: 'haplotypes',
        type: "VARCHAR(255) DEFAULT ''",
        columnNameInTable: 'Haplotypes',
        ruColumnNameInTable: 'Haplotypes',
        isDigit: false,
    },
    {
        name: 'rha',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'RHA',
        ruColumnNameInTable: 'RHA',
        isDigit: true,
    },
    {
        name: 'efi',
        type: 'FLOAT DEFAULT 0',
        columnNameInTable: 'EFI',
        ruColumnNameInTable: 'EFI',
        isDigit: true,
    },
    {
        name: 'birth_date',
        type: "VARCHAR(16) DEFAULT ''",
        columnNameInTable: 'Birth Date',
        ruColumnNameInTable: 'Дата рождения',
        isDigit: false,
    },
    {
        name: 'proof',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'Proof',
        ruColumnNameInTable: 'Оценка',
        isDigit: false,
    },
    {
        name: 'adv',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'ADV',
        ruColumnNameInTable: 'ADV',
        isDigit: false,
    },
    {
        name: 'gs',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'GS',
        ruColumnNameInTable: 'GS',
        isDigit: false,
    },
    {
        name: 'fs',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'FS',
        ruColumnNameInTable: 'FS',
        isDigit: false,
    },
    {
        name: 'num_511',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: '511',
        ruColumnNameInTable: '511',
        isDigit: false,
    },
    {
        name: 'edge',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'EDGE',
        ruColumnNameInTable: 'EDGE',
        isDigit: false,
    },
    {
        name: 'cp',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'CP',
        ruColumnNameInTable: 'CP',
        isDigit: false,
    },
    {
        name: 'cp511',
        type: "VARCHAR(64) DEFAULT ''",
        columnNameInTable: 'CP511',
        ruColumnNameInTable: 'CP511',
        isDigit: false,
    },
];
